In [8]:
import numpy as np

In [9]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [10]:
l = np.random.rand(4,5)

In [11]:
l

array([[0.02705504, 0.53077961, 0.72832677, 0.47703485, 0.61214694],
       [0.81821648, 0.56245221, 0.13930821, 0.57661019, 0.56167481],
       [0.88484383, 0.17768668, 0.94416341, 0.24446864, 0.6302933 ],
       [0.43001669, 0.31267364, 0.22347476, 0.50082535, 0.47193893]])

In [12]:
l.shape

(4, 5)

In [13]:
n = np.random.rand(10)

In [14]:
m = np.random.rand(10)

In [15]:
np.dot(n,m)

np.float64(1.578758186661746)

In [16]:
n.shape

(10,)

In [17]:
n = np.random.rand(5,2)

In [18]:
l

array([[0.02705504, 0.53077961, 0.72832677, 0.47703485, 0.61214694],
       [0.81821648, 0.56245221, 0.13930821, 0.57661019, 0.56167481],
       [0.88484383, 0.17768668, 0.94416341, 0.24446864, 0.6302933 ],
       [0.43001669, 0.31267364, 0.22347476, 0.50082535, 0.47193893]])

In [19]:
(l.shape, n.shape)

((4, 5), (5, 2))

In [20]:
def m_m_multiply (u, v):
    assert u.shape[1] == v.shape[0]

    df = np.zeros((u.shape[0],v.shape[1]))

    for i in range(u.shape[0]):
        for j in range(v.shape[1]):
            df[i][j] = np.dot(u[i],v[:,j])

    return df

In [21]:
k = m_m_multiply(l,n)

In [22]:
k

array([[1.26308374, 1.06129423],
       [1.00775284, 0.62453389],
       [1.20870292, 1.11286192],
       [0.82357414, 0.58176444]])

In [23]:
l.dot(n)

array([[1.26308374, 1.06129423],
       [1.00775284, 0.62453389],
       [1.20870292, 1.11286192],
       [0.82357414, 0.58176444]])

In [24]:
m = np.random.randint(0, 10, (5,5))

In [25]:
m

array([[3, 7, 3, 1, 8],
       [6, 0, 2, 9, 2],
       [1, 9, 1, 9, 2],
       [9, 2, 2, 6, 2],
       [7, 1, 9, 6, 9]])

In [26]:
m_inv = np.linalg.inv(m)

In [27]:
m_inv.dot(m)

array([[ 1.00000000e+00,  1.42247325e-16,  5.89805982e-17,
         2.08166817e-17,  8.67361738e-17],
       [-5.89805982e-17,  1.00000000e+00,  5.89805982e-17,
        -3.67761377e-16,  2.25514052e-16],
       [ 1.38777878e-16, -5.55111512e-16,  1.00000000e+00,
        -3.88578059e-16, -1.38777878e-16],
       [ 1.14491749e-16,  2.42861287e-17,  2.42861287e-17,
         1.00000000e+00, -8.67361738e-17],
       [-2.08166817e-16,  4.16333634e-17, -1.38777878e-17,
         7.49400542e-16,  1.00000000e+00]])